### ISSUE TITLE
2장 객체 생성과 파괴 - 정리내용 발표자료 등록하기

### ISSUE THREAD

**Issue by moto6** [d-h-k/Effective-Java-Study#100]
### 장 끝난거 - 정리내용 발표자료 등록하실분은 댓글로 남겨주세요(아래 양식)
--------
n아이템 : [링크]

**Comment by moto6** [comment]
## (예시)

- 아이템1 : https://github.com/d-h-k/Effective-Java-Study/blob/main/dong/item1.md
- 아이템5 : https://github.com/d-h-k/Effective-Java-Study/blob/main/dong/item5.md
- 아이템6 : https://github.com/d-h-k/Effective-Java-Study/blob/main/dong/item6.md

**Comment by ghojeong** [comment]
# Pyro

- 아이템2: https://github.com/d-h-k/Effective-Java-Study/blob/main/pyro/item2.md
- 아이템5: https://github.com/d-h-k/Effective-Java-Study/blob/main/pyro/item5.md
- 아이템9: https://github.com/d-h-k/Effective-Java-Study/blob/main/pyro/item9.md
